apiVersion: v1
kind: Pod
metadata:
  name: openshift-boohkub-web-api
  labels:
    name: openshift-bookhub-web-api
spec:
  containers:
    - name: bookhub-webapi-app
      image: 540468/pv179:webapi
      env:
        - name: ASPNETCORE_URLS
          value: http://+:5000
        - name: ASPNETCORE_ENVIRONMENT
          value: Production        
      ports:
        - name: web
          containerPort: 5000
      volumeMounts:
        - name: bookhub-volume 
          mountPath: /app/data
  securityContext:
      supplementalGroups: [100003] 
      privileged: false
  volumes:
    - name: bookhub-volume
      persistentVolumeClaim:
        claimName: bookhub-pvc-web-api
