apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookhub-pvc-web-api
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
volumeBindingMode: Immediate