image: "mcr.microsoft.com/dotnet/sdk:7.0"

variables:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
    DOTNET_CLI_TELEMETRY_OPTOUT: "true"

before_script:
    - dotnet restore ./PV179_BookHub/PV179_BookHub.sln

stages:
    - build
    - test

build:
    stage: build
    script:
        - dotnet build --configuration Release ./PV179_BookHub/PV179_BookHub.sln

test:
    stage: test
    script:
        - dotnet test --configuration Release ./PV179_BookHub/PV179_BookHub.sln
