@startuml
' visual settings
!theme cerulean-outline
hide circle
skinparam backgroundColor white

left to right direction

actor Admin as adm
actor Manager as mgr
actor User as usr

usr <|-- mgr
mgr <|-- adm



rectangle BookHub {
note "For simplicity, 'manage' can be considered \n as standard set of CRUD operations." as nt

usecase (Log in/out) as auth
usecase (Manage Book Stores) as M_store
usecase (Manage His Book Store Inventory) as M_inv
usecase (Manage His Account) as M_acc
usecase (Manage His Orders) as M_ord
usecase (Manage His Wishlists) as M_wish
usecase (View Books) as R_book
usecase (Manage His Book Ratings) as Rate_book
usecase (Manage Books) as M_book
}

note "The Admin is allowed to Manage Accounts, \n Orders, etc. of other Users and Managers as well." as adm_note
adm .. adm_note

usr --> auth
usr --> M_acc
usr --> M_ord
usr --> M_wish
usr --> R_book
usr --> Rate_book

adm --> M_store
adm --> M_book

mgr --> M_inv

@enduml
