apiVersion: v1
kind: Pod
metadata:
  name: openshift-boohkub 
  labels:
    name: openshift-bookhub
spec:
  containers:
    - name: bookhub-mvc-app
      image: 540468/pv179:mvc
      env:
        - name: ASPNETCORE_URLS
          value: http://+:5000
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
      ports:
        - name: web
          containerPort: 5000
      volumeMounts:
        - name: bookhub-volume 
          mountPath: /app/data
  securityContext:
      supplementalGroups: [100003] 
      privileged: false
  volumes:
    - name: bookhub-volume
      persistentVolumeClaim:
        claimName: bookhub-pvc
